spring.application.name=match-organizer
spring.datasource.url=jdbc:postgresql://localhost:5432/match
spring.datasource.username=ayushman
spring.datasource.password=Ayush@123
spring.jpa.hibernate.ddl-auto=update
